// Typed access to the compiled data (generated by scripts/build-data.ts).
// Run `npm run build:data` if these imports fail — generated/ is a build artifact.
import taxonomyJson from './generated/taxonomy.json';
import kbJson from './generated/kb.json';
import type { Taxonomy, KnowledgeBase, Category } from './types.ts';

export const taxonomy = taxonomyJson as Taxonomy;
export const knowledgeBase = kbJson as KnowledgeBase;

export const categories: Category[] = taxonomy.categories;
export const categoryByName: ReadonlyMap<string, Category> = new Map(categories.map((c) => [c.name, c]));
export const categoryByCode: ReadonlyMap<string, Category> = new Map(categories.map((c) => [c.code, c]));
